### ISSUE TITLE
Problem: SDP governance gives no guidance on what vision to pursue

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/DAO#11]
Usually organizations follow a purpose or a vision. But SDP has neither of that. Hence to many members it's difficult to make decision that would require falling back on a vision, strategy and tactics.

**Comment by johba37** [comment]
except the name, which talks about dist0rting the social protocols 😬

**Comment by TimDaub** [comment]
Well, to me it's clear how dist0rtion can be used. But I would prefer we had a shared but dist0rted understanding

**Comment by TimDaub** [comment]
> except the name, which talks about dist0rting the social protocols 😬

If you'd be on the mailing list you'd know that right now we're "social distancing protocol". I don't like it, I'd prefer if we were spacial distancing protocol.

**Comment by TimDaub** [comment]
anyways, closing for now.
