### ISSUE TITLE
Draft ToCO2 LOU for event organizers

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/DAO#2]
## problem

absence of document to create binding agreement with event organizers.

## solution
Draft LOU for event organizers. Letter of Understanding should contain:
- Detailed summary of the work to be performed
- Tasks of the service provider and the receiver
- Milestones for the work to be done

## estimated effort
~5h / 350 SDP

## payment conditions
- written LOU
- reviewer by owners

**Comment by vrde** [comment]
:+1:

**Comment by johba37** [comment]
delivered here: https://hackmd.io/6YDFihp4RJ6gxJepG7_G3g
