### ISSUE TITLE
Problem: A proposal *must* contain a problem _and_ a solution

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/DAO#5]
DIP-001 states that a proposal *must* (see #7) always contain a problem and a solution. But sometimes a problem can exist for long without a solution. But in this case we, the contributors, still might want to create an issue already to have greater peace of mind.

## Solution

Make it optional to provide a solution to a problem (e.g. "SHOULD").

**Comment by vrde** [comment]
Wouldn't this be just an **issue**? Also, SDP governance is the sum af all proposals (see DIP-001):

> Governance is the sum of all Dist0rtion Improvement Proposals (DIPs) contained in the master branch of this repository.

How does a problem definition itself add value to the governance?

**Comment by TimDaub** [comment]
Touché
