### ISSUE TITLE
create a German version of Corona tracing app

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/DAO#9]
https://github.com/DP-3T 

wouldn't a German version of this be something for social distortion protocol? show that open source can be more effective that big corporate hierarchies. Being installed on 70% of mobiles would also be a great platform to launch a kiez token or something.

**Comment by vrde** [comment]
What is the rationale to put contact tracing and a token together in an app? Even if done with the best of intentions I doubt that people would perceive this as an advantage.

As far as I know the Android app [supports German already](https://github.com/DP-3T/dp3t-app-android#introduction). Switzerland is going towards [the adoption of DP-3T](https://www.swissinfo.ch/eng/digital-solution_contact-tracing-app-could-be-launched-in-switzerland-within-weeks/45706296), do you know any organization lobbying to push the German government to use a free and open source solution for that?

Also, I don't know enough about how (and if) Germany wants to implement contact tracing.

**Comment by TimDaub** [comment]
What's the underlying problem?

Edit: asking @johannbarbie

**Comment by johba37** [comment]
> What is the rationale to put contact tracing and a token together in an app?

none, it was just an idea to use the traction. another one would be advertisement, or branding the app with a certain political party, to give them some success-washing (green party scrambling for attention).

> do you know any organization lobbying to push the German government to use a free and open source solution for that?

there has been a decision to use DP-3T, so i understand that any ready app using that protocol would be accepted. If there is an working app already, great, let's use it.

> Also, I don't know enough about how (and if) Germany wants to implement contact tracing.

see previous question. there is consensus on the protocol, every-one is waiting for an implementation, but they don't know about the agility of open source. 

> What's the underlying problem?

corona is infectious 2 days before one sees symptoms. having the app infection chains can be broken by informing and voluntary self-isolation of contacts.

**Comment by TimDaub** [comment]
Relevant:

- https://www.ccc.de/de/updates/2020/contact-tracing-requirements


In any case, I don't see how SDP could be in a position right now to implement a contact tracing app. In the future possibly, but not with the current governance in place.

**Comment by johba37** [comment]
what is wrong with the governance? :)

**Comment by TimDaub** [comment]
see #11

**Comment by johba37** [comment]
i wouldn't discredit a bunch of cools guys because they don't have a purpose. sometimes a project that creates traction can introduce the purpose.
cc @vrde
